### ISSUE TITLE
Exception after exception - code is not running

### ISSUE THREAD

**Issue by toshaklg** [rymc/n2d#18]
Hello!
I hope there are still people hanging around in the repo and maybe know the issue. After completing the steps described in readme I got errors if I try to run the model. Here is what I got:

> /home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/lowering.py", line 328, in lower_inst
    self.storevar(val, inst.target.name)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/lowering.py", line 1278, in storevar
    raise AssertionError(msg)
AssertionError: Storing i64 to ptr of i32 ('dim'). FE type int32

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "n2d.py", line 15, in <module>
    import umap
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/umap/__init__.py", line 1, in <module>
    from .umap_ import UMAP
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/umap/umap_.py", line 54, in <module>
    from umap.layouts import (
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/umap/layouts.py", line 36, in <module>
    "dim": numba.types.int32,
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/decorators.py", line 221, in wrapper
    disp.compile(sig)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/dispatcher.py", line 111, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/compiler.py", line 395, in _compile_core
    raise e
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/typed_passes.py", line 463, in run_pass
    NativeLowering().run_pass(state)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/typed_passes.py", line 384, in run_pass
    lower.lower()
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Storing i64 to ptr of i32 ('dim'). FE type int32

>File "../miniconda3/envs/n2d2/lib/python3.7/site-packages/umap/layouts.py", line 52:
def rdist(x, y):
    <source elided>
    result = 0.0
    dim = x.shape[0]
    ^

>During: lowering "dim = static_getitem(value=$8load_attr.2, index=0, index_var=$const10.3, fn=<built-in function getitem>)" at /home/anton/miniconda3/envs/n2d2/lib/python3.7/site-packages/umap/layouts.py (52)

Tested on Ubuntu 20.04 running through WSL2 and on another workstation with Ubuntu 18.04.
Any ideas what have I done wrong?

Thanks.

**Comment by toshaklg** [comment]
Alright, downgrading numba solved the problem:
```
pip uninstall numba
pip install numba==0.52.0
```
